name: Artifact app
on:
  pull_request:
    types:
      - opened
    branches:
      - 'master'
      - 'main'
      - 'dev'
      - 'releases/**'
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
      - 'releases/**'
    paths:
      - '.github/workflows/*'
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up node
              uses: actions/setup-node@v4
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Run Lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        outputs:
            html-file: ${{ steps.publish.outputs.html-file }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up node
              uses: actions/setup-node@v4
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Test code
              run: npm run test
            - name: Publish index html filename
              id: publish
              run: find index.html -type f -execdir echo 'html-file={}' >> $GITHUB_OUTPUT ';'
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: public-files
                path: |
                    public
                    package.json
    deploy:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up node
              uses: actions/setup-node@v4
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Build code
              run: npm run build
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: public-files
            - name: List directory
              run: ls
            - name: Output filename
              run: echo "${{ needs.test.outputs.html-file }}"
            - name: Deploy
              run: echo "Deployed"