name: Conditionals Practice
on: 
    workflow_dispatch:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        outputs:
            test-report: ${{ steps.report.outputs.test-report }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up node
              uses: actions/setup-node@v4
            # - name: Cache
            #   id: cache
            #   uses: actions/cache@v4
            #   with:
            #     path: node_modules
            #     key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
            #   if: steps.cache.outputs.cache-hit == 'false'
              run: npm ci
            - name: Run Test
              id: run-test
              run: npm run test
            - name: Generate Report
              id: report
              if: failure() && steps.run-test.outcome == 'failure'
              run: echo "test-report='test-failed'" >> $GITHUB_OUTPUT
    report:
        needs: test
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Generate Report
              run: echo "${{ needs.test.outputs.test-report }}"
            