name: Conditionals
on:
    push:
    workflow_dispatch:
jobs:
    test:
        runs-on: ubuntu-latest
        outputs:
            report-output: ${{ steps.report.outputs.report-output}}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up node
              uses: actions/setup-node@v4
            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Test code
              id: run-test
              run: npm run test
            - name: Generate Report
              id: report
              if: failure() && steps.run-test.outcome == 'failure'
              run: echo "report-output='hello'" >> $GITHUB_OUTPUT