name: Reusable Test
on: 
    workflow_call:
        inputs:
            output-value:
                description: Add Test Inputs
                required: true
                type: string
                default: succeeded
        outputs:
            test-result: 
                value: ${{ jobs.test.outputs.test-result }}
jobs:
    test:
        outputs: 
            test-result: ${{ steps.test-result.outputs.test-output }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest, windows-latest]
                node-version: [16, 18, 21]
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up Node
              uses: actions/setup-node@v4
            - name: Install Dependencies
              uses: npm ci
            - name: Run Test
              run: npm run test
            - name: result
              id: test-result
              run: echo "test-output=${{inputs.output-value}}" >> $GITHUB_OUTPUT
              
