name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name: 
                description: This is a test
                required: false
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}
            - name: list code
              run: ls
            - name: Display Output
              run: echo "Deploying from reusable worflow"