name: Reusable Test
on: 
    workflow_call:
jobs:
    okay:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Set-up Node
              uses: actions/setup-node@v4
            - name: Install Dependencies
              uses: npm ci
            - name: Run Test
              run: npm run test
              
