name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name: 
                description: This is a test
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: The result
                value: ${{ jobs.deploy.outputs.result }}
jobs:
    deploy:
        outputs:
            result: ${{ steps.result.outputs.result }}
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}
            - name: list code
              run: ls
            - name: Display Output
              id: result
              run: echo "result='success'" >> $GITHUB_OUTPUT