name: Test Script
on: 
    workflow_dispatch:
    push:
jobs:
    hello:
        uses: ./.github/workflows/reusablev2.yml
        with:
            output-value: succeeded
    hi:
        needs: hello
        runs-on: ubuntu-latest
        steps:
            - name: Get result
              run: echo ${{ needs.hello.outputs.test-result }}
