name: Test Script
on: 
    workflow_dispatch:
    push:
jobs:
    test:
        uses: ./.github/workflows/reusablev2.yml
        with:
            output-value: failed
    result:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get result
              run: echo ${{ needs.test.outputs }}